### PR TITLE
Feat wishlist page

### PR DESCRIPTION
**Pull request by junaidshaikh-js**
Added wishlist page 

Preview: https://deploy-preview-5--autodecore.netlify.app/wishlist.html

### CODE REVIEW

**Review by stutisk — COMMENTED** [review]
looks good to me!

**Review by devananth — APPROVED** [review]
Code seems to be clean. Good work !

**Review by MaruthiPothuganti — APPROVED** [review]
Looks good to merge

**Review by raghav2110 — COMMENTED** [review]
Looks good sir . Good to merge

**Pull request merged**
